### ISSUE TITLE
inspect.getargspec removed in Python 3.11

### ISSUE THREAD

**Issue by varakirill** [AlexxIT/Dataplicity#21]
Logger: m2m
Source: /usr/local/lib/python3.11/site-packages/dataplicity/m2m/wsclient.py:268
First occurred: 16:49:52 (1 occurrences)
Last logged: 16:49:52
error handling websocket event

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/dataplicity/m2m/wsclient.py", line 266, in run
    self.on_event(event)
  File "/usr/local/lib/python3.11/site-packages/dataplicity/m2m/wsclient.py", line 282, in on_event
    self.on_binary(event.data)
  File "/usr/local/lib/python3.11/site-packages/dataplicity/m2m/wsclient.py", line 328, in on_binary
    self.on_packet(packet)
  File "/usr/local/lib/python3.11/site-packages/dataplicity/m2m/wsclient.py", line 348, in on_packet
    self.dispatcher.dispatch(packet_type, packet_body)
  File "/usr/local/lib/python3.11/site-packages/dataplicity/m2m/dispatcher.py", line 80, in dispatch
    return self.dispatch_packet(packet)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataplicity/m2m/dispatcher.py", line 92, in dispatch_packet
    arg_spec = inspect.getargspec(method)
               ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'

**Comment by Gferretta** [comment]
Idem

Not working in 2023.6

🤦‍♂️😔

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/Dataplicity/releases/tag/v1.1.0

**Comment by YVladislavovich** [comment]
thanks for the great work!

**Comment by Fierys** [comment]
Thank you! After upgrading to v1.1.0 - everything works!
